In [2]:
# TASK 1 : Create a 1D array of numbers from 0 to 9

import numpy as np

array = np.array ([0,1,2,3,4,5,6,7,8,9])

print  (array [0:10])


[0 1 2 3 4 5 6 7 8 9]


In [3]:
# TASK 2 : Create a 3×3 NumPy array of all Boolean value Trues

import numpy as np

array = np.bool(3,3)

print (array)

True
<ipython-input-3-efb8c64b516f>:5: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  array =np.bool (8)


In [13]:
# TASK 3 :Extract all odd numbers from array of 1-10

import numpy as np

array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8 , 9, 10])

array = np.arange(-1, 10 ,2)  

print(array)




[-1  1  3  5  7  9]


In [11]:
#TASK 4: Replace all odd numbers in an array of 1-10 with the value -1.

import numpy as np 
 
array = np.array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]) 

odd = (array%2 == 1 )
array [odd] = -1

print (array [odd])

[-1 -1 -1 -1 -1]


In [10]:
#TASK 5 :Convert a 1D array to a 2D array with 2 rows
#TASK 6 :Create two arrays a and b, stack these two arrays vertically use the  np.dot and np.sum to calculatetotals

import numpy as np

array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22])

NewA = np.arange (1,11).reshape (5,2)
NewB = np.arange (12,22).reshape (5,2)

array2D = np.dot (NewA, NewB)

Calc = np.sum(array2D,axis = 2)

print (Calc)



ValueError: shapes (5,2) and (5,2) not aligned: 2 (dim 1) != 5 (dim 0)

In [ ]:
# Extension:1.Create the following pattern without hardcoding.

